name: Build scheduled-build
on:
  schedule:
    # 2週間に1回実行する
    - cron: '0 0 */2 * *'

jobs:
  pushed_build:
    name: Build(pushed)
    if: (github.repository == 'yukari-seno/kuroco-sample-nuxt2' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
        continue-on-error: true
      - name: Generate
        run: npm run generate
        # - name: Zip artifact for upload
        #  run: cd dist && zip ../dist.zip . -r
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}-${{ github.run_id }}
          path: dist
          retention-days: 7
      - name: Webhook
        uses: diverta/workflow-webhook@v2
        env:
          webhook_url: "https://mex-dev.g.kuroco.app/direct/menu/github/"
          webhook_secret: "2b19e71337f953b5658f7ea726524879"
          data: '{"single_zip":"0","domain":"mex-dev.g.kuroco-front.app", "repository":"${{ github.repository }}", "run_id":"${{ github.run_id }}", "hash":"${{ github.sha }}"}'
